source "https://rubygems.org"
group :jekyll_plugins do
  gem "jekyll", "~> 4.0" 
  gem "jekyll-feed", "~> 0.6"
  gem "jekyll-gist"
  gem "jektex", "~> 0.1.0"
  gem "jekyll-scholar", "~> 7.1.3"
  gem "bibtex-ruby", "~> 6.0.0"
  gem "jekyll-toc"
  gem "jekyll-seo-tag"
  gem "jekyll-include-cache"
  gem "kramdown-parser-gfm"
  gem "rouge"
  gem "webrick"
end
